theme: jekyll-theme-minimal
title: Veve One
description: World First Open Source Virtual Character
logo: https://raw.githubusercontent.com/veve1/minimal/master/assets/img/ED7D48D4-6F55-4F58-BF39-2130BDDDEF7A.jpeg
