theme: jekyll-theme-minimal
title: Veve One
description: World First Open Source Virtual Character
logo: https://raw.githubusercontent.com/veve1/resources/master/EB3AB69D-3065-4740-AFA9-BDFEAF2B0469.jpeg
